Writing Functions


In [1]:
import numpy

In [2]:
def calculate_distance(atom1_coord, atom2_coord):
    pass

In [3]:
print(calculate_distance)

<function calculate_distance at 0x00000250690DB880>


In [4]:
def calculate_distance(atom1_coord, atom2_coord):
    x_distance = atom1_coord[0] - atom2_coord[0]

In [5]:
def calculate_distance(atom1_coord, atom2_coord):
    x_distance = atom1_coord[0] - atom2_coord[0]
    y_distance = atom1_coord[1] - atom2_coord[1]

In [6]:
def calculate_distance(atom1_coord, atom2_coord):
    x_distance = atom1_coord[0] - atom2_coord[0]
    y_distance = atom1_coord[1] - atom2_coord[1]
    z_distance = atom1_coord[2] - atom2_coord[2]

In [7]:
def calculate_distance(atom1_coord, atom2_coord):
    x_distance = atom1_coord[0] - atom2_coord[0]
    y_distance = atom1_coord[1] - atom2_coord[1]
    z_distance = atom1_coord[2] - atom2_coord[2]

    bond_length_12 = numpy.sqrt(
        x_distance ** 2 +
        y_distance ** 2 +
        z_distance ** 2
    )

    return bond_length_12

In [8]:
atom1 = [0.0, 0.0, 0.0]
atom2 = [0.0, 0.0, 1.0]

distance = calculate_distance(atom1, atom2)

print(distance)

1.0


In [9]:
import os

file_location = os.path.join('data', 'water.xyz')

xyz_file = numpy.genfromtxt(
    fname=file_location,
    skip_header=2,
    dtype='unicode'
)

symbols = xyz_file[:, 0]
coordinates = xyz_file[:, 1:]

coordinates = coordinates.astype(float)

print(symbols)
print(coordinates)

['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [10]:
num_atoms = len(symbols)

print(num_atoms)

3


In [11]:
for num1 in range(0, num_atoms):
    print(num1)

0
1
2


In [12]:
for num1 in range(0, num_atoms):
    for num2 in range(0, num_atoms):
        print(num1, num2)

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2


In [13]:
for num1 in range(0, num_atoms):
    for num2 in range(0, num_atoms):
        if num1 < num2:
            print(num1, num2)

0 1
0 2
1 2


In [14]:
for num1 in range(0, num_atoms):
    for num2 in range(0, num_atoms):
        if num1 < num2:
            bond_length_12 = calculate_distance(
                coordinates[num1],
                coordinates[num2]
            )
            print(bond_length_12)

0.9690005374652793
0.9690003348647513
1.52693633514957


In [15]:
def bond_check(atom_distance):
    if atom_distance > 0 and atom_distance <= 1.5:
        return True
    else:
        return False

In [16]:
print(bond_check(1.0))
print(bond_check(1.5))
print(bond_check(1.6))

True
True
False


In [17]:
for num1 in range(0, num_atoms):
    for num2 in range(0, num_atoms):
        if num1 < num2:
            bond_length_12 = calculate_distance(
                coordinates[num1],
                coordinates[num2]
            )

            if bond_check(bond_length_12):
                print(
                    symbols[num1],
                    symbols[num2],
                    bond_length_12
                )

O H1 0.9690005374652793
O H2 0.9690003348647513


In [18]:
print(
    symbols[num1],
    symbols[num2],
    bond_length_12
)

H2 H2 1.52693633514957


In [19]:
def bond_check(atom_distance, minimum_length, maximum_length):
    if atom_distance > minimum_length and atom_distance <= maximum_length:
        return True
    else:
        return False

In [20]:
print(bond_check(1.0, 0, 1.5))
print(bond_check(1.5, 0, 1.5))
print(bond_check(1.6, 0, 1.5))

True
True
False


In [21]:
minimum_length = 0
maximum_length = 1.5

print(minimum_length)
print(maximum_length)

0
1.5


In [22]:
bond_check(
    bond_length_12,
    minimum_length,
    maximum_length
)

False

In [ ]:
def open_xyz(filename):
    xyz_file = numpy.genfromtxt(fname=filename, skip_header=2, dtype='unicode')
    symbols = xyz_file[:, 0]
    coord = xyz_file[:, 1:]
    coord = coord.astype(numpy.float)
    return symbols, coord

In [24]:
import numpy
import os

def calculate_distance(atom1_coord, atom2_coord):
    """
    Calculate the distance between two three-dimensional points.
    """
    x_distance = atom1_coord[0] - atom2_coord[0]
    y_distance = atom1_coord[1] - atom2_coord[1]
    z_distance = atom1_coord[2] - atom2_coord[2]
    bond_length_12 = numpy.sqrt(x_distance ** 2 + y_distance ** 2 + z_distance ** 2)
    return bond_length_12

def bond_check(atom_distance, minimum_length=0, maximum_length=1.5):
    """Check if a distance is a bond based on a minimum and maximum bond length"""

    if atom_distance > minimum_length and atom_distance <= maximum_length:
        return True
    else:
        return False

def open_xyz(filename):
     """
     Open and read an xyz file. Returns tuple of symbols and coordinates.
     """
     xyz_file = numpy.genfromtxt(fname=filename, skip_header=2, dtype='unicode')
     symbols = xyz_file[:,0]
     coord = (xyz_file[:,1:])
     coord = coord.astype(numpy.float)
     return symbols, coord

def print_bonds(atom_symbols, atom_coordinates):
    """
    Prints atom symbols and bond length for a set of atoms.
    """
    num_atoms = len(atom_symbols)
    for num1 in range(0, num_atoms):
        for num2 in range(0, num_atoms):
            if num1 < num2:
                bond_length_12 = calculate_distance(atom_coordinates[num1], atom_coordinates[num2])
                if bond_check(bond_length_12) is True:
                    print(F'{atom_symbols[num1]} to {atom_symbols[num2]} : {bond_length_12:.3f}')

In [28]:
def open_xyz(filename):
    xyz_file = numpy.loadtxt(filename, skiprows=2, dtype=str)

    symbols = xyz_file[:, 0]
    coord = xyz_file[:, 1:]

    coord = coord.astype(float)

    return symbols, coord

In [29]:
water_file_location = os.path.join('data', 'water.xyz')
water_symbols, water_coords = open_xyz(water_file_location)

benzene_file_location = os.path.join('data', 'benzene.xyz')
benzene_symbols, benzene_coords = open_xyz(benzene_file_location)

print(F'Printing bonds for water.')
print_bonds(water_symbols, water_coords)

print(F'Printing bonds for benzene.')
print_bonds(benzene_symbols, benzene_coords)

Printing bonds for water.
O to H1 : 0.969
O to H2 : 0.969
Printing bonds for benzene.
C to H : 1.088
C to C : 1.403
C to C : 1.403
C to H : 1.088
C to C : 1.403
C to H : 1.088
C to C : 1.403
C to H : 1.088
C to C : 1.403
C to H : 1.088
C to C : 1.403
C to H : 1.088
