# Working with Tabular Data

## Lesson 4

Python Scripting for Computational Molecular Science

In [1]:
import numpy

In [2]:
help(numpy.genfromtxt)

Help on function genfromtxt in module numpy:

genfromtxt(
    fname,
    dtype=<class 'float'>,
    comments='#',
    delimiter=None,
    skip_header=0,
    skip_footer=0,
    converters=None,
    missing_values=None,
    filling_values=None,
    usecols=None,
    names=None,
    excludelist=None,
    deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~",
    replace_space='_',
    autostrip=False,
    case_sensitive=True,
    defaultfmt='f%i',
    unpack=None,
    usemask=False,
    loose=True,
    invalid_raise=True,
    max_rows=None,
    encoding=None,
    *,
    ndmin=0,
    like=None
)
    Load data from a text file, with missing values handled as specified.

    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.

    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension

In [3]:
data = numpy.genfromtxt(
    "data/distance_data_headers.csv",
    dtype="unicode",
    delimiter=","
)

In [4]:
print(data)

[['Frame' 'THR4_ATP' 'THR4_ASP' 'TYR6_ATP' 'TYR6_ASP']
 ['1' '8.9542' '5.8024' '11.5478' '9.9557']
 ['2' '8.6181' '6.0942' '13.9594' '11.6945']
 ...
 ['9998' '8.6625' '7.7306' '9.5469' '10.3063']
 ['9999' '9.2456' '7.8886' '9.8151' '10.7564']
 ['10000' '8.8135' '7.917' '9.9517' '10.7848']]


In [5]:
type(data)

numpy.ndarray

In [6]:
data.shape

(10001, 5)

In [7]:
data[0]

array(['Frame', 'THR4_ATP', 'THR4_ASP', 'TYR6_ATP', 'TYR6_ASP'],
      dtype='<U8')

In [8]:
data[1]

array(['1', '8.9542', '5.8024', '11.5478', '9.9557'], dtype='<U8')

In [9]:
data[0][0]

np.str_('Frame')

In [10]:
import os
import numpy

In [11]:
distance_file = os.path.join(
    "data",
    "distance_data_headers.csv"
)

In [12]:
print(distance_file)

data\distance_data_headers.csv


In [15]:
distances = numpy.genfromtxt(
    fname=distance_file,
    delimiter=",",
    dtype="unicode"
)

In [16]:
print(distances)

[['Frame' 'THR4_ATP' 'THR4_ASP' 'TYR6_ATP' 'TYR6_ASP']
 ['1' '8.9542' '5.8024' '11.5478' '9.9557']
 ['2' '8.6181' '6.0942' '13.9594' '11.6945']
 ...
 ['9998' '8.6625' '7.7306' '9.5469' '10.3063']
 ['9999' '9.2456' '7.8886' '9.8151' '10.7564']
 ['10000' '8.8135' '7.917' '9.9517' '10.7848']]


In [17]:
type(distance_file)

str

In [18]:
type(distances)

numpy.ndarray

In [19]:
import os

distance_file = os.path.join('data', 'distance_data_headers.csv')

distances = numpy.genfromtxt(fname=distance_file, delimiter=',', dtype='unicode')
print(distances)

[['Frame' 'THR4_ATP' 'THR4_ASP' 'TYR6_ATP' 'TYR6_ASP']
 ['1' '8.9542' '5.8024' '11.5478' '9.9557']
 ['2' '8.6181' '6.0942' '13.9594' '11.6945']
 ...
 ['9998' '8.6625' '7.7306' '9.5469' '10.3063']
 ['9999' '9.2456' '7.8886' '9.8151' '10.7564']
 ['10000' '8.8135' '7.917' '9.9517' '10.7848']]


In [20]:
headers = distances[0]
print(headers)

['Frame' 'THR4_ATP' 'THR4_ASP' 'TYR6_ATP' 'TYR6_ASP']


In [21]:
data = distances[1:]
print(data)

[['1' '8.9542' '5.8024' '11.5478' '9.9557']
 ['2' '8.6181' '6.0942' '13.9594' '11.6945']
 ['3' '9.0066' '6.0637' '13.0924' '11.3043']
 ...
 ['9998' '8.6625' '7.7306' '9.5469' '10.3063']
 ['9999' '9.2456' '7.8886' '9.8151' '10.7564']
 ['10000' '8.8135' '7.917' '9.9517' '10.7848']]


In [22]:
data = data.astype(float)

In [23]:
print(type(data))

<class 'numpy.ndarray'>


In [24]:
print(data[0,1])
print(data[1,0])

8.9542
2.0


In [25]:
small_data = data[0:10,0:3]
print(small_data)

[[ 1.      8.9542  5.8024]
 [ 2.      8.6181  6.0942]
 [ 3.      9.0066  6.0637]
 [ 4.      9.2002  6.0227]
 [ 5.      9.1294  5.9365]
 [ 6.      9.0462  6.2553]
 [ 7.      8.8657  5.9186]
 [ 8.      9.3256  6.2351]
 [ 9.      9.4184  6.1993]
 [10.      9.06    6.0478]]


In [26]:
print(small_data[5,:])
print(small_data[:,1:])

[6.     9.0462 6.2553]
[[8.9542 5.8024]
 [8.6181 6.0942]
 [9.0066 6.0637]
 [9.2002 6.0227]
 [9.1294 5.9365]
 [9.0462 6.2553]
 [8.8657 5.9186]
 [9.3256 6.2351]
 [9.4184 6.1993]
 [9.06   6.0478]]


In [3]:
thr4_atp = data[:,1]

NameError: name 'data' is not defined

In [4]:
import os
import numpy

In [5]:
distance_file = os.path.join(
    "data",
    "distance_data_headers.csv"
)

In [6]:
distances = numpy.genfromtxt(
    fname=distance_file,
    delimiter=",",
    dtype="unicode"
)

In [7]:
headers = distances[0]

In [8]:
data = distances[1:]

In [9]:
data = data.astype(float)

In [10]:
thr4_atp = data[:,1]

In [11]:
print(thr4_atp)

[8.9542 8.6181 9.0066 ... 8.6625 9.2456 8.8135]


In [12]:
avg_thr4_atp = numpy.mean(thr4_atp)

In [13]:
print(avg_thr4_atp)

10.876950930000001


In [14]:
num_columns = len(data[0,:])

print(num_columns)

5


In [15]:
for i in range(1,5):
    print(i)

1
2
3
4


In [16]:
for i in range(1,num_columns):
    print(i)

1
2
3
4


In [17]:
for i in range(1,num_columns):
    print(headers[i])

THR4_ATP
THR4_ASP
TYR6_ATP
TYR6_ASP


In [18]:
for i in range(1,num_columns):
    column = data[:,i]
    print(column)

[8.9542 8.6181 9.0066 ... 8.6625 9.2456 8.8135]
[5.8024 6.0942 6.0637 ... 7.7306 7.8886 7.917 ]
[11.5478 13.9594 13.0924 ...  9.5469  9.8151  9.9517]
[ 9.9557 11.6945 11.3043 ... 10.3063 10.7564 10.7848]


In [19]:
for i in range(1,num_columns):
    column = data[:,i]
    avg_col = numpy.mean(column)
    print(avg_col)

10.876950930000001
7.342344959999999
11.20979133
10.9934435


In [20]:
for i in range(1,num_columns):
    column = data[:,i]
    avg_col = numpy.mean(column)
    print(f"{headers[i]} : {avg_col}")


THR4_ATP : 10.876950930000001
THR4_ASP : 7.342344959999999
TYR6_ATP : 11.20979133
TYR6_ASP : 10.9934435


In [1]:
import numpy
import os

In [2]:
file_location = os.path.join('data','water.xyz')

In [3]:
xyz_file = numpy.genfromtxt(
    fname=file_location,
    skip_header=2,
    dtype='unicode'
)

In [4]:
symbols = xyz_file[:,0]

In [5]:
coordinates = xyz_file[:,1:]

In [6]:
coordinates = coordinates.astype(float)

In [7]:
num_atoms = len(symbols)

In [10]:
for num1 in range(0, num_atoms):
    print(num1)

0
1
2


In [11]:
print(num_atoms)

3


In [12]:
for num1 in range(0, num_atoms):
    print(num1)

0
1
2


In [13]:
for num1 in range(0, num_atoms):
    for num2 in range(0, num_atoms):
        print(num1, num2)

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2


In [14]:
for num1 in range(0, num_atoms):
    for num2 in range(0, num_atoms):
        print(symbols[num1], "to", symbols[num2])

O to O
O to H1
O to H2
H1 to O
H1 to H1
H1 to H2
H2 to O
H2 to H1
H2 to H2


In [15]:
for num1 in range(0, num_atoms):
    for num2 in range(0, num_atoms):
        x_distance = coordinates[num1, 0] - coordinates[num2, 0]
        print(x_distance)

0.0
0.0
0.0
-0.0
0.0
-0.0
0.0
0.0
0.0


In [16]:
for num1 in range(0, num_atoms):
    for num2 in range(0, num_atoms):
        x_distance = coordinates[num1, 0] - coordinates[num2, 0]
        y_distance = coordinates[num1, 1] - coordinates[num2, 1]
        z_distance = coordinates[num1, 2] - coordinates[num2, 2]

        print(x_distance, y_distance, z_distance)

0.0 0.0 0.0
0.0 -0.008642 0.968962
0.0 -0.9381820000000001 -0.24243800000000004
-0.0 0.008642 -0.968962
0.0 0.0 0.0
-0.0 -0.92954 -1.2114
0.0 0.9381820000000001 0.24243800000000004
0.0 0.92954 1.2114
0.0 0.0 0.0


In [17]:
for num1 in range(0, num_atoms):
    for num2 in range(0, num_atoms):
        x_distance = coordinates[num1, 0] - coordinates[num2, 0]
        y_distance = coordinates[num1, 1] - coordinates[num2, 1]
        z_distance = coordinates[num1, 2] - coordinates[num2, 2]

        bond_length_12 = numpy.sqrt(
            x_distance**2 +
            y_distance**2 +
            z_distance**2
        )

        print(bond_length_12)

0.0
0.9690005374652793
0.9690003348647513
0.9690005374652793
0.0
1.52693633514957
0.9690003348647513
1.52693633514957
0.0


In [18]:
for num1 in range(0, num_atoms):
    for num2 in range(0, num_atoms):
        x_distance = coordinates[num1, 0] - coordinates[num2, 0]
        y_distance = coordinates[num1, 1] - coordinates[num2, 1]
        z_distance = coordinates[num1, 2] - coordinates[num2, 2]

        bond_length_12 = numpy.sqrt(
            x_distance**2 +
            y_distance**2 +
            z_distance**2
        )

        print(f"{symbols[num1]} to {symbols[num2]} : {bond_length_12:.3f}")

O to O : 0.000
O to H1 : 0.969
O to H2 : 0.969
H1 to O : 0.969
H1 to H1 : 0.000
H1 to H2 : 1.527
H2 to O : 0.969
H2 to H1 : 1.527
H2 to H2 : 0.000
